//! Emit `src/lib.rs` for the wasm-component bridge.
//!
//! Phase 2: real dispatch for a curated set of scalar functions
//! (see `dispatch::registry`). The match arm for each entry
//! marshals SQL value args → WIT-typed args, invokes the
//! imported `postgis:wasm/*` function, and marshals the result
//! back to a SQL value — same shape as the hand-written
//! `extensions/postgis-bridge` (the implementation oracle).
//! Scalars not in the registry still return the Phase 1 stub
//! error so the full ~931-scalar surface stays loadable while
//! Phase 3 grows the dispatch table to coverage parity.
//!
//! Aggregates remain stubbed at Phase 2; the same dispatch
//! pattern applies, but aggregates need a per-context state
//! object that's deferred to Phase 3.
//!
//! The shape mirrors `extensions/postgis-bridge/src/lib.rs`:
//! `wit_bindgen::generate!` against `wit/world.wit`,
//! `impl MetadataGuest / ScalarFunctionGuest / AggregateGuest /
//! VtabGuest for $Bridge`. The metadata manifest reflects every
//! scalar/aggregate the interface DB declares so the host's
//! `describe()` returns the full surface even when most
//! functions are still stubbed.

use std::collections::HashMap;

use crate::core::BridgePlan;
use crate::wasm_target::dispatch;

/// Generate `src/lib.rs`. `crate_name` is the bridge crate
/// name (e.g. "postgis-sqlink-bridge"); used only inside the
/// emitted stub error strings.
pub fn lib_rs(plan: &BridgePlan, crate_name: &str) -> String {
    let primary = plan
        .extensions
        .first()
        .map(|e| e.name.as_str())
        .unwrap_or("shim");

    // Bridge struct name in PascalCase.
    let bridge_struct = pascal_case(primary) + "Bridge";

    // Build the (scalar_name → func_id) lookup the dispatcher
    // needs. The id assignment must match the metadata emitter's
    // pass below — both walk plan.extensions in the same order
    // and assign scalar ids starting at 1.
    let scalar_id_for = build_scalar_id_index(plan);

    let mut s = String::new();
    s.push_str(HEADER);
    s.push_str(&format!(
        r##"//! Generated by sqlink-shim-codegen (Phase 2).
//!
//! Bridges {primary} onto sqlite:extension/* as a wasm
//! component. Scalars listed in the codegen dispatch registry
//! get real marshaling logic; the rest still return the Phase 1
//! stub error so the full ~931-function surface stays
//! describable while Phase 3 scales coverage.

#![allow(unused_imports, dead_code)]

extern crate alloc;

use alloc::format;
use alloc::string::{{String, ToString}};
use alloc::vec::Vec;

mod bindings {{
    wit_bindgen::generate!({{
        path: "wit",
        world: "bridge",
        generate_all,
    }});
}}

use bindings::exports::sqlite::extension::aggregate_function::Guest as AggregateGuest;
use bindings::exports::sqlite::extension::metadata::{{
    AggregateFunctionSpec, Guest as MetadataGuest, Manifest, ScalarFunctionSpec,
}};
use bindings::exports::sqlite::extension::scalar_function::Guest as ScalarFunctionGuest;
use bindings::exports::sqlite::extension::vtab::{{
    ConstraintUsage, Guest as VtabGuest, IndexInfo, IndexPlan, VtabRow,
}};
use bindings::sqlite::extension::types::{{FunctionFlags, SqlValue}};

// Imported `postgis:wasm/*` interfaces. Aliased to match the
// hand-written bridge's naming so emitted dispatch arms look the
// same. Phase 1's DCE-anchor is gone  the real match arms below
// keep these imports live naturally.
use bindings::postgis::wasm::postgis_accessors as pg_acc;
use bindings::postgis::wasm::postgis_constructors as pg_ctor;
use bindings::postgis::wasm::postgis_measurements as pg_meas;
use bindings::postgis::wasm::postgis_output as pg_out;
use bindings::postgis::wasm::postgis_predicates as pg_pred;
use bindings::postgis::wasm::postgis_processing as pg_proc;
use bindings::postgis::wasm::postgis_types::{{Geometry, PostgisError}};

const BRIDGE_NAME: &str = "{crate_name}";

/// Marker for functions not yet covered by Phase 2's dispatch
/// registry. The host's caller surfaces this back to the user
/// verbatim, so the Phase 3 work item ("expand registry") is
/// self-documenting from the error string.
fn stubbed(kind: &str, func_id: u64) -> String {{
    format!(
        "{{BRIDGE_NAME}}: {{kind}} func_id={{func_id}} is stubbed (not in Phase 2 dispatch registry; \
         see PLAN-codegen-retarget.md Phase 3 for coverage scale-up)",
        BRIDGE_NAME = BRIDGE_NAME,
        kind = kind,
        func_id = func_id,
    )
}}

// ── Argument-unpack helpers ──
//
// Mirror the hand-written `extensions/postgis-bridge/src/lib.rs`
// versions so dispatch arms emitted here look identical to the
// oracle. Each returns `Err(String)` shaped like
// "{{name}}: arg {{idx}} must be TYPE" so the SQL-side error
// surface is consistent.

fn arg_text<'a>(args: &'a [SqlValue], idx: usize, name: &str) -> Result<&'a str, String> {{
    match args.get(idx) {{
        Some(SqlValue::Text(s)) => Ok(s.as_str()),
        _ => Err(format!("{{name}}: arg {{idx}} must be TEXT")),
    }}
}}

fn arg_blob<'a>(args: &'a [SqlValue], idx: usize, name: &str) -> Result<&'a [u8], String> {{
    match args.get(idx) {{
        Some(SqlValue::Blob(b)) => Ok(b.as_slice()),
        // Geometry that arrived as text is accepted as raw bytes
        // for parity with the hand-written bridge; some PostGIS
        // tests pass WKB-shaped values via TEXT literals.
        Some(SqlValue::Text(s)) => Ok(s.as_bytes()),
        _ => Err(format!("{{name}}: arg {{idx}} must be BLOB")),
    }}
}}

fn arg_f64(args: &[SqlValue], idx: usize, name: &str) -> Result<f64, String> {{
    match args.get(idx) {{
        Some(SqlValue::Real(r)) => Ok(*r),
        Some(SqlValue::Integer(i)) => Ok(*i as f64),
        _ => Err(format!("{{name}}: arg {{idx}} must be REAL")),
    }}
}}

fn from_wkb(bytes: &[u8], name: &str) -> Result<Geometry, String> {{
    Geometry::from_wkb(bytes).map_err(|e| format!("{{name}}: {{}}", postgis_err_string(e)))
}}

/// Format a `postgis-error` variant back to a string the SQL
/// caller can read. Mirrors the helper in the hand-written
/// bridge.
fn postgis_err_string(e: PostgisError) -> String {{
    match e {{
        PostgisError::InvalidGeometry(s)
        | PostgisError::ParseError(s)
        | PostgisError::UnsupportedOperation(s)
        | PostgisError::NumericError(s)
        | PostgisError::SridMismatch(s)
        | PostgisError::General(s) => s,
    }}
}}

struct {bridge_struct};

"##,
        primary = primary,
        crate_name = crate_name,
        bridge_struct = bridge_struct,
    ));

    // MetadataGuest impl — reflect every scalar / aggregate from
    // the interface DB into the manifest. The manifest is what
    // the host reads at load time; populating it correctly means
    // .load registers ~931 PostGIS scalars + 34 aggregates as
    // SQLite functions even though most bodies are stubs.
    s.push_str(&emit_metadata_impl(plan, &bridge_struct));

    // ScalarFunctionGuest impl — dispatches registry-listed
    // scalars to their real marshaling code; everything else
    // falls back to the stub error.
    s.push_str(&emit_scalar_impl(&bridge_struct, &scalar_id_for));

    // AggregateGuest impl — Phase 2 leaves these stubbed; the
    // sites/state-object plumbing is Phase 3 work.
    s.push_str(&format!(
        r##"impl AggregateGuest for {bridge_struct} {{
    fn step(func_id: u64, _context_id: u64, _args: Vec<SqlValue>) -> Result<(), String> {{
        Err(stubbed("aggregate-function step", func_id))
    }}
    fn finalize(func_id: u64, _context_id: u64) -> Result<SqlValue, String> {{
        Err(stubbed("aggregate-function finalize", func_id))
    }}
    fn value(func_id: u64, _context_id: u64) -> Result<SqlValue, String> {{
        Err(stubbed("aggregate-function value", func_id))
    }}
    fn inverse(func_id: u64, _context_id: u64, _args: Vec<SqlValue>) -> Result<(), String> {{
        Err(stubbed("aggregate-function inverse", func_id))
    }}
}}

"##,
        bridge_struct = bridge_struct,
    ));

    // VtabGuest impl — all methods stubbed so the bridge wasm
    // satisfies the `vtab` export the world declares. Phase 1
    // doesn't expose any vtabs (manifest.vtabs is empty), so the
    // host won't actually invoke these at runtime  but they
    // must exist as Guest items for the export to resolve.
    s.push_str(&format!(
        r##"impl VtabGuest for {bridge_struct} {{
    fn create(
        vtab_id: u64,
        _instance_id: u64,
        _db_name: String,
        _table_name: String,
        _args: Vec<String>,
    ) -> Result<String, String> {{
        Err(stubbed("vtab create", vtab_id))
    }}
    fn connect(
        vtab_id: u64,
        _instance_id: u64,
        _db_name: String,
        _table_name: String,
        _args: Vec<String>,
    ) -> Result<String, String> {{
        Err(stubbed("vtab connect", vtab_id))
    }}
    fn destroy(vtab_id: u64, _instance_id: u64) -> Result<(), String> {{
        Err(stubbed("vtab destroy", vtab_id))
    }}
    fn disconnect(vtab_id: u64, _instance_id: u64) -> Result<(), String> {{
        Err(stubbed("vtab disconnect", vtab_id))
    }}
    fn best_index(
        vtab_id: u64,
        _instance_id: u64,
        _info: IndexInfo,
    ) -> Result<IndexPlan, String> {{
        Err(stubbed("vtab best-index", vtab_id))
    }}
    fn open(vtab_id: u64, _instance_id: u64, _cursor_id: u64) -> Result<(), String> {{
        Err(stubbed("vtab open", vtab_id))
    }}
    fn close(vtab_id: u64, _cursor_id: u64) -> Result<(), String> {{
        Err(stubbed("vtab close", vtab_id))
    }}
    fn filter(
        vtab_id: u64,
        _cursor_id: u64,
        _idx_num: i32,
        _idx_str: Option<String>,
        _args: Vec<SqlValue>,
    ) -> Result<(), String> {{
        Err(stubbed("vtab filter", vtab_id))
    }}
    fn next(vtab_id: u64, _cursor_id: u64) -> Result<(), String> {{
        Err(stubbed("vtab next", vtab_id))
    }}
    fn eof(_vtab_id: u64, _cursor_id: u64) -> bool {{
        true
    }}
    fn column(vtab_id: u64, _cursor_id: u64, _col: i32) -> Result<SqlValue, String> {{
        Err(stubbed("vtab column", vtab_id))
    }}
    fn rowid(vtab_id: u64, _cursor_id: u64) -> Result<i64, String> {{
        Err(stubbed("vtab rowid", vtab_id))
    }}
    fn fetch_batch(
        vtab_id: u64,
        _cursor_id: u64,
        _max_rows: u32,
    ) -> Result<Vec<VtabRow>, String> {{
        Err(stubbed("vtab fetch-batch", vtab_id))
    }}
}}

bindings::export!({bridge_struct} with_types_in bindings);
"##,
        bridge_struct = bridge_struct,
    ));

    s
}

/// Emit `impl ScalarFunctionGuest for $Bridge` with one match
/// arm per dispatch-registry entry. The runtime ids come from
/// the precomputed `scalar_id_for` map so they line up with the
/// metadata emitter.
fn emit_scalar_impl(bridge_struct: &str, scalar_id_for: &HashMap<&str, u64>) -> String {
    let mut arms = String::new();
    for entry in dispatch::registry() {
        let Some(&id) = scalar_id_for.get(entry.sql_name) else {
            // The interface DB doesn't actually declare this
            // scalar  skip silently. Phase 3 should treat this
            // as an error once the registry is generated rather
            // than hand-listed.
            continue;
        };
        let body = dispatch::emit_arm_body(&entry.shape, entry.sql_name, "                ");
        arms.push_str(&format!(
            "            {id} => {{\n{body}\n            }}\n",
            id = id,
            body = body,
        ));
    }

    format!(
        r##"
impl ScalarFunctionGuest for {bridge_struct} {{
    fn call(func_id: u64, args: Vec<SqlValue>) -> Result<SqlValue, String> {{
        match func_id {{
{arms}            _ => Err(stubbed("scalar-function", func_id)),
        }}
    }}
}}

"##,
        bridge_struct = bridge_struct,
        arms = arms,
    )
}

/// Build the (scalar canonical-name + alias) → func-id map.
/// Mirrors the assignment loop inside `emit_metadata_impl`
/// exactly so the dispatcher and the manifest stay in agreement.
fn build_scalar_id_index(plan: &BridgePlan) -> HashMap<&str, u64> {
    let mut idx = HashMap::new();
    let mut id: u64 = 1;
    for ext in &plan.extensions {
        for sc in &ext.scalars {
            idx.insert(sc.canonical_name.as_str(), id);
            id += 1;
            for alias in &sc.aliases {
                idx.insert(alias.as_str(), id);
                id += 1;
            }
        }
    }
    idx
}

/// Emit `impl MetadataGuest for $Bridge`. The describe() result
/// enumerates every scalar / aggregate the interface DB lists so
/// the host registers the full surface even at Phase 2 (most
/// function bodies remain stubbed).
fn emit_metadata_impl(plan: &BridgePlan, bridge_struct: &str) -> String {
    let primary = plan
        .extensions
        .first()
        .map(|e| e.name.as_str())
        .unwrap_or("shim");

    // Build the scalar + aggregate entries. We use stable
    // sequential function IDs starting at 1 so the host has
    // something deterministic to dispatch against.
    //
    // Convention: scalar ids start at 1, aggregate ids start at
    // 1_000_000  big enough that scalars and aggregates can't
    // collide even at full PostGIS surface (~317 scalars).
    let mut scalar_entries = String::new();
    let mut scalar_id: u64 = 1;
    for ext in &plan.extensions {
        for sc in &ext.scalars {
            let num_args = scalar_num_args(sc);
            push_scalar_entry(
                &mut scalar_entries,
                scalar_id,
                &sc.canonical_name,
                num_args,
                sc.is_deterministic,
            );
            scalar_id += 1;
            for alias in &sc.aliases {
                push_scalar_entry(
                    &mut scalar_entries,
                    scalar_id,
                    alias,
                    num_args,
                    sc.is_deterministic,
                );
                scalar_id += 1;
            }
        }
    }

    let mut agg_entries = String::new();
    let mut agg_id: u64 = 1_000_000;
    for ext in &plan.extensions {
        for ag in &ext.aggregates {
            let num_args = aggregate_num_args(ag);
            push_aggregate_entry(&mut agg_entries, agg_id, &ag.canonical_name, num_args);
            agg_id += 1;
            for alias in &ag.aliases {
                push_aggregate_entry(&mut agg_entries, agg_id, alias, num_args);
                agg_id += 1;
            }
        }
    }

    let version = plan
        .extensions
        .first()
        .map(|e| e.version.as_str())
        .unwrap_or("0.1.0");

    format!(
        r##"impl MetadataGuest for {bridge_struct} {{
    fn describe() -> Manifest {{
        let det = FunctionFlags::DETERMINISTIC;
        let utf8 = FunctionFlags::empty();

        let _ = utf8;

        let scalar_functions: Vec<ScalarFunctionSpec> = alloc::vec![
{scalar_entries}        ];
        let aggregate_functions: Vec<AggregateFunctionSpec> = alloc::vec![
{agg_entries}        ];

        Manifest {{
            name: "{primary}".into(),
            version: "{version}".into(),
            scalar_functions,
            aggregate_functions,
            collations: alloc::vec![],
            vtabs: alloc::vec![],
            dot_commands: alloc::vec![],
            has_authorizer: false,
            has_update_hook: false,
            has_commit_hook: false,
            has_wal_hook: false,
            wal_hook_id: 0,
            declared_capabilities: alloc::vec![],
            optional_capabilities: alloc::vec![],
            preferred_prefix: None,
            prefix_expansion: None,
        }}
    }}
}}

"##,
        bridge_struct = bridge_struct,
        primary = primary,
        version = version,
        scalar_entries = scalar_entries,
        agg_entries = agg_entries,
    )
}

fn push_scalar_entry(out: &mut String, id: u64, name: &str, num_args: i32, det: bool) {
    let flags = if det { "det" } else { "FunctionFlags::empty()" };
    out.push_str(&format!(
        "            ScalarFunctionSpec {{ id: {id}, name: \"{name}\".into(), num_args: {num_args}, func_flags: {flags} }},\n",
        id = id,
        name = name.replace('"', "\\\""),
        num_args = num_args,
        flags = flags,
    ));
}

fn push_aggregate_entry(out: &mut String, id: u64, name: &str, num_args: i32) {
    out.push_str(&format!(
        "            AggregateFunctionSpec {{ id: {id}, name: \"{name}\".into(), num_args: {num_args}, func_flags: FunctionFlags::empty(), is_window: false }},\n",
        id = id,
        name = name.replace('"', "\\\""),
        num_args = num_args,
    ));
}

fn scalar_num_args(sc: &crate::core::ScalarFn) -> i32 {
    let variants = &sc.param_signatures;
    if variants.is_empty() {
        return -1;
    }
    let first = variants[0].len();
    if variants.iter().all(|v| v.len() == first) {
        first as i32
    } else {
        -1
    }
}

fn aggregate_num_args(ag: &crate::core::AggregateFn) -> i32 {
    let variants = &ag.param_signatures;
    if variants.is_empty() {
        return -1;
    }
    let first = variants[0].len();
    if variants.iter().all(|v| v.len() == first) {
        first as i32
    } else {
        -1
    }
}

fn pascal_case(s: &str) -> String {
    let mut out = String::new();
    let mut up = true;
    for c in s.chars() {
        if c == '-' || c == '_' || c.is_whitespace() {
            up = true;
            continue;
        }
        if up {
            for u in c.to_uppercase() {
                out.push(u);
            }
            up = false;
        } else {
            out.push(c);
        }
    }
    out
}

const HEADER: &str =
    "// === GENERATED by sqlink-shim-codegen (target=wasm-component)  do not edit by hand ===\n\n";
