//! Emit `src/lib.rs` for the wasm-component bridge.
//!
//! Phase 1: stubs everywhere. Every exported guest function
//! returns its `Err(...)` variant with a marker string so the
//! load + register + call path can be exercised end-to-end
//! before Phase 2 supplies real dispatch.
//!
//! The shape mirrors `extensions/postgis-bridge/src/lib.rs`:
//! `wit_bindgen::generate!` against `wit/world.wit`,
//! `impl MetadataGuest / ScalarFunctionGuest / AggregateGuest /
//! VtabGuest for $Bridge`. The metadata manifest reflects every
//! scalar/aggregate the interface DB declares so the host's
//! `describe()` call returns a non-empty surface even at
//! Phase 1.

use crate::core::BridgePlan;

/// Generate `src/lib.rs`. `crate_name` is the bridge crate
/// name (e.g. "postgis-sqlink-bridge"); used only inside the
/// emitted stub error strings.
pub fn lib_rs(plan: &BridgePlan, crate_name: &str) -> String {
    let primary = plan
        .extensions
        .first()
        .map(|e| e.name.as_str())
        .unwrap_or("shim");

    // Bridge struct name in PascalCase.
    let bridge_struct = pascal_case(primary) + "Bridge";

    let mut s = String::new();
    s.push_str(HEADER);
    s.push_str(&format!(
        r##"//! Generated by sqlink-shim-codegen (Phase 1 stub).
//!
//! Bridges {primary} onto sqlite:extension/* as a wasm
//! component. Phase 1 emits stub bodies for every exported
//! function  the load + compose + describe path works, calls
//! return a marker error so end-to-end validation can confirm
//! the shape without real dispatch wired up.

#![allow(unused_imports, dead_code)]

extern crate alloc;

use alloc::format;
use alloc::string::{{String, ToString}};
use alloc::vec::Vec;

mod bindings {{
    wit_bindgen::generate!({{
        path: "wit",
        world: "bridge",
        generate_all,
    }});
}}

use bindings::exports::sqlite::extension::aggregate_function::Guest as AggregateGuest;
use bindings::exports::sqlite::extension::metadata::{{
    AggregateFunctionSpec, Guest as MetadataGuest, Manifest, ScalarFunctionSpec,
}};
use bindings::exports::sqlite::extension::scalar_function::Guest as ScalarFunctionGuest;
use bindings::exports::sqlite::extension::vtab::{{
    ConstraintUsage, Guest as VtabGuest, IndexInfo, IndexPlan, VtabRow,
}};
use bindings::sqlite::extension::types::{{FunctionFlags, SqlValue}};

// Phase 1: keep the upstream postgis imports live so wac plug
// has a non-empty plug surface. The hand-written bridge in
// sqlink/extensions/postgis-bridge calls these symbols
// throughout its scalar/aggregate dispatch; Phase 2 reproduces
// that mechanically and removes this anchor. For Phase 1 we
// just need at least one import to survive dead-code
// elimination so the composed wasm has the expected provenance
// (bridge + postgis-composed).
use bindings::postgis::wasm::postgis_constructors as pg_ctor;
use bindings::postgis::wasm::postgis_accessors as pg_acc;
use bindings::postgis::wasm::postgis_measurements as pg_meas;
use bindings::postgis::wasm::postgis_predicates as pg_pred;
use bindings::postgis::wasm::postgis_output as pg_out;

const BRIDGE_NAME: &str = "{crate_name}";

/// Phase 1 stub marker. Returned by every dispatch entry point
/// so a caller can confirm the shape works without forcing
/// Phase 2's marshaling logic to be ready.
fn stubbed(kind: &str, func_id: u64) -> String {{
    format!(
        "{{BRIDGE_NAME}}: {{kind}} func_id={{func_id}} is stubbed in Phase 1 \
         (see PLAN-codegen-retarget.md Phase 2 for real dispatch)",
        BRIDGE_NAME = BRIDGE_NAME,
        kind = kind,
        func_id = func_id,
    )
}}

/// Phase 1 import anchor. Never invoked at runtime  the
/// `unreachable!()` after the calls aborts before any postgis
/// import fires  but the linker keeps the imports live because
/// the call sites compile in. Phase 2 deletes this when the
/// real dispatch table starts using these imports for actual
/// work.
#[doc(hidden)]
#[no_mangle]
pub extern "C" fn __phase1_postgis_import_anchor(seed: f64) -> f64 {{
    // Guard so the anchor never fires in real execution. The
    // `core::hint::black_box` calls below are still emitted by
    // the codegen, which is what keeps the WIT imports linked
    // into the component.
    if seed.is_nan() {{
        let g = pg_ctor::st_make_point(seed, seed);
        let _ = core::hint::black_box(pg_acc::st_x(&g));
        let _ = core::hint::black_box(pg_meas::st_area(&g));
        let _ = core::hint::black_box(pg_pred::st_intersects(&g, &g));
        let _ = core::hint::black_box(pg_out::st_as_text(&g));
    }}
    seed
}}

struct {bridge_struct};

"##,
        primary = primary,
        crate_name = crate_name,
        bridge_struct = bridge_struct,
    ));

    // MetadataGuest impl — reflect every scalar / aggregate from
    // the interface DB into the manifest. The manifest is what
    // the host reads at load time; populating it correctly means
    // .load registers ~317 PostGIS function names as SQLite
    // functions even though their bodies are stubs.
    s.push_str(&emit_metadata_impl(plan, &bridge_struct));

    // ScalarFunctionGuest impl — every call returns Err.
    s.push_str(&format!(
        r##"
impl ScalarFunctionGuest for {bridge_struct} {{
    fn call(func_id: u64, _args: Vec<SqlValue>) -> Result<SqlValue, String> {{
        Err(stubbed("scalar-function", func_id))
    }}
}}

"##,
        bridge_struct = bridge_struct,
    ));

    // AggregateGuest impl — likewise stubbed.
    s.push_str(&format!(
        r##"impl AggregateGuest for {bridge_struct} {{
    fn step(func_id: u64, _context_id: u64, _args: Vec<SqlValue>) -> Result<(), String> {{
        Err(stubbed("aggregate-function step", func_id))
    }}
    fn finalize(func_id: u64, _context_id: u64) -> Result<SqlValue, String> {{
        Err(stubbed("aggregate-function finalize", func_id))
    }}
    fn value(func_id: u64, _context_id: u64) -> Result<SqlValue, String> {{
        Err(stubbed("aggregate-function value", func_id))
    }}
    fn inverse(func_id: u64, _context_id: u64, _args: Vec<SqlValue>) -> Result<(), String> {{
        Err(stubbed("aggregate-function inverse", func_id))
    }}
}}

"##,
        bridge_struct = bridge_struct,
    ));

    // VtabGuest impl — all methods stubbed so the bridge wasm
    // satisfies the `vtab` export the world declares. Phase 1
    // doesn't expose any vtabs (manifest.vtabs is empty), so the
    // host won't actually invoke these at runtime  but they
    // must exist as Guest items for the export to resolve.
    s.push_str(&format!(
        r##"impl VtabGuest for {bridge_struct} {{
    fn create(
        vtab_id: u64,
        _instance_id: u64,
        _db_name: String,
        _table_name: String,
        _args: Vec<String>,
    ) -> Result<String, String> {{
        Err(stubbed("vtab create", vtab_id))
    }}
    fn connect(
        vtab_id: u64,
        _instance_id: u64,
        _db_name: String,
        _table_name: String,
        _args: Vec<String>,
    ) -> Result<String, String> {{
        Err(stubbed("vtab connect", vtab_id))
    }}
    fn destroy(vtab_id: u64, _instance_id: u64) -> Result<(), String> {{
        Err(stubbed("vtab destroy", vtab_id))
    }}
    fn disconnect(vtab_id: u64, _instance_id: u64) -> Result<(), String> {{
        Err(stubbed("vtab disconnect", vtab_id))
    }}
    fn best_index(
        vtab_id: u64,
        _instance_id: u64,
        _info: IndexInfo,
    ) -> Result<IndexPlan, String> {{
        Err(stubbed("vtab best-index", vtab_id))
    }}
    fn open(vtab_id: u64, _instance_id: u64, _cursor_id: u64) -> Result<(), String> {{
        Err(stubbed("vtab open", vtab_id))
    }}
    fn close(vtab_id: u64, _cursor_id: u64) -> Result<(), String> {{
        Err(stubbed("vtab close", vtab_id))
    }}
    fn filter(
        vtab_id: u64,
        _cursor_id: u64,
        _idx_num: i32,
        _idx_str: Option<String>,
        _args: Vec<SqlValue>,
    ) -> Result<(), String> {{
        Err(stubbed("vtab filter", vtab_id))
    }}
    fn next(vtab_id: u64, _cursor_id: u64) -> Result<(), String> {{
        Err(stubbed("vtab next", vtab_id))
    }}
    fn eof(_vtab_id: u64, _cursor_id: u64) -> bool {{
        true
    }}
    fn column(vtab_id: u64, _cursor_id: u64, _col: i32) -> Result<SqlValue, String> {{
        Err(stubbed("vtab column", vtab_id))
    }}
    fn rowid(vtab_id: u64, _cursor_id: u64) -> Result<i64, String> {{
        Err(stubbed("vtab rowid", vtab_id))
    }}
    fn fetch_batch(
        vtab_id: u64,
        _cursor_id: u64,
        _max_rows: u32,
    ) -> Result<Vec<VtabRow>, String> {{
        Err(stubbed("vtab fetch-batch", vtab_id))
    }}
}}

bindings::export!({bridge_struct} with_types_in bindings);
"##,
        bridge_struct = bridge_struct,
    ));

    s
}

/// Emit `impl MetadataGuest for $Bridge`. The describe() result
/// enumerates every scalar / aggregate the interface DB lists so
/// the host registers the full surface even at Phase 1.
fn emit_metadata_impl(plan: &BridgePlan, bridge_struct: &str) -> String {
    let primary = plan
        .extensions
        .first()
        .map(|e| e.name.as_str())
        .unwrap_or("shim");

    // Build the scalar + aggregate entries. We use stable
    // sequential function IDs starting at 1 so the host has
    // something deterministic to dispatch against.
    //
    // Convention: scalar ids start at 1, aggregate ids start at
    // 1_000_000  big enough that scalars and aggregates can't
    // collide even at full PostGIS surface (~317 scalars).
    let mut scalar_entries = String::new();
    let mut scalar_id: u64 = 1;
    for ext in &plan.extensions {
        for sc in &ext.scalars {
            let num_args = scalar_num_args(sc);
            push_scalar_entry(
                &mut scalar_entries,
                scalar_id,
                &sc.canonical_name,
                num_args,
                sc.is_deterministic,
            );
            scalar_id += 1;
            for alias in &sc.aliases {
                push_scalar_entry(
                    &mut scalar_entries,
                    scalar_id,
                    alias,
                    num_args,
                    sc.is_deterministic,
                );
                scalar_id += 1;
            }
        }
    }

    let mut agg_entries = String::new();
    let mut agg_id: u64 = 1_000_000;
    for ext in &plan.extensions {
        for ag in &ext.aggregates {
            let num_args = aggregate_num_args(ag);
            push_aggregate_entry(&mut agg_entries, agg_id, &ag.canonical_name, num_args);
            agg_id += 1;
            for alias in &ag.aliases {
                push_aggregate_entry(&mut agg_entries, agg_id, alias, num_args);
                agg_id += 1;
            }
        }
    }

    let version = plan
        .extensions
        .first()
        .map(|e| e.version.as_str())
        .unwrap_or("0.1.0");

    format!(
        r##"impl MetadataGuest for {bridge_struct} {{
    fn describe() -> Manifest {{
        let det = FunctionFlags::DETERMINISTIC;
        let utf8 = FunctionFlags::empty();

        let _ = utf8;

        let scalar_functions: Vec<ScalarFunctionSpec> = alloc::vec![
{scalar_entries}        ];
        let aggregate_functions: Vec<AggregateFunctionSpec> = alloc::vec![
{agg_entries}        ];

        Manifest {{
            name: "{primary}".into(),
            version: "{version}".into(),
            scalar_functions,
            aggregate_functions,
            collations: alloc::vec![],
            vtabs: alloc::vec![],
            dot_commands: alloc::vec![],
            has_authorizer: false,
            has_update_hook: false,
            has_commit_hook: false,
            has_wal_hook: false,
            wal_hook_id: 0,
            declared_capabilities: alloc::vec![],
            optional_capabilities: alloc::vec![],
            preferred_prefix: None,
            prefix_expansion: None,
        }}
    }}
}}

"##,
        bridge_struct = bridge_struct,
        primary = primary,
        version = version,
        scalar_entries = scalar_entries,
        agg_entries = agg_entries,
    )
}

fn push_scalar_entry(out: &mut String, id: u64, name: &str, num_args: i32, det: bool) {
    let flags = if det { "det" } else { "FunctionFlags::empty()" };
    out.push_str(&format!(
        "            ScalarFunctionSpec {{ id: {id}, name: \"{name}\".into(), num_args: {num_args}, func_flags: {flags} }},\n",
        id = id,
        name = name.replace('"', "\\\""),
        num_args = num_args,
        flags = flags,
    ));
}

fn push_aggregate_entry(out: &mut String, id: u64, name: &str, num_args: i32) {
    out.push_str(&format!(
        "            AggregateFunctionSpec {{ id: {id}, name: \"{name}\".into(), num_args: {num_args}, func_flags: FunctionFlags::empty(), is_window: false }},\n",
        id = id,
        name = name.replace('"', "\\\""),
        num_args = num_args,
    ));
}

fn scalar_num_args(sc: &crate::core::ScalarFn) -> i32 {
    let variants = &sc.param_signatures;
    if variants.is_empty() {
        return -1;
    }
    let first = variants[0].len();
    if variants.iter().all(|v| v.len() == first) {
        first as i32
    } else {
        -1
    }
}

fn aggregate_num_args(ag: &crate::core::AggregateFn) -> i32 {
    let variants = &ag.param_signatures;
    if variants.is_empty() {
        return -1;
    }
    let first = variants[0].len();
    if variants.iter().all(|v| v.len() == first) {
        first as i32
    } else {
        -1
    }
}

fn pascal_case(s: &str) -> String {
    let mut out = String::new();
    let mut up = true;
    for c in s.chars() {
        if c == '-' || c == '_' || c.is_whitespace() {
            up = true;
            continue;
        }
        if up {
            for u in c.to_uppercase() {
                out.push(u);
            }
            up = false;
        } else {
            out.push(c);
        }
    }
    out
}

const HEADER: &str =
    "// === GENERATED by sqlink-shim-codegen (target=wasm-component)  do not edit by hand ===\n\n";
