//! Emit the `README.md` for the wasm-component bridge crate.

use crate::core::BridgePlan;

pub fn readme(plan: &BridgePlan, crate_name: &str) -> String {
    let primary = plan
        .extensions
        .first()
        .map(|e| e.name.as_str())
        .unwrap_or("shim");
    let version = plan
        .extensions
        .first()
        .map(|e| e.version.as_str())
        .unwrap_or("0.1.0");

    let (sc, ag, tf, wf, ct, op, cw, pp, sct, idx) = match plan.extensions.first() {
        Some(e) => (
            e.scalars.len(),
            e.aggregates.len(),
            e.table_functions.len(),
            e.window_functions.len(),
            e.column_types.len(),
            e.operators.len(),
            e.cast_rewrites.len(),
            e.preprocessor_patterns.len(),
            e.system_catalog_tables.len(),
            e.spatial_indexes.len(),
        ),
        None => (0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
    };

    format!(
        r##"# {crate_name}

Generated by [`sqlink-shim-codegen`](https://github.com/zacharywhitley/sqlink-shim-codegen)
from `{primary}-interface.sqlite` with `--target wasm-component`.

**Do not edit by hand**  regenerate from the interface DB.

## Phase 1 status (per `PLAN-codegen-retarget.md`)

This crate is a **Phase 1 STUB**. The shape compiles + composes
+ loads; every exported function body returns a marker error
(`{crate_name}: ... is stubbed in Phase 1`). Phase 2 replaces
the stubs with real marshaling logic.

## Surface from the interface DB

| extension | version | scalars | aggregates | UDTFs | windows | types | operators | casts | preprocessors | catalog | indexes |
|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|
| {primary} | {version} | {sc} | {ag} | {tf} | {wf} | {ct} | {op} | {cw} | {pp} | {sct} | {idx} |

## Build (Phase 1)

```sh
cargo build --target wasm32-wasip2 --release
```

The build needs `wit-bindgen` and an installed `wasm32-wasip2`
target (`rustup target add wasm32-wasip2`).

## Compose with the upstream shim wasm

```sh
wac plug \
  --plug ~/git/postgis-wasm/postgis-composed.wasm \
  -o {primary}-sqlink-loadable.wasm \
  target/wasm32-wasip2/release/{crate_underscore}.wasm
```

The resulting `{primary}-sqlink-loadable.wasm` is what
sqlink-host's `load_extension*` path consumes.

## Verify (Phase 1)

```sh
wasm-tools validate {primary}-sqlink-loadable.wasm
```

Then load via sqlink-host and call any function  expect the
stub error variant.

## Regenerate

```sh
cd ~/git/sqlink-shim-codegen
cargo run --release -- \
  --target wasm-component \
  --interface /path/to/{primary}-interface.sqlite \
  --out ~/git/{crate_name}
```

## License

Apache-2.0.
"##,
        crate_name = crate_name,
        crate_underscore = crate_name.replace('-', "_"),
        primary = primary,
        version = version,
        sc = sc,
        ag = ag,
        tf = tf,
        wf = wf,
        ct = ct,
        op = op,
        cw = cw,
        pp = pp,
        sct = sct,
        idx = idx,
    )
}
